
  (function($){

    if (screen.width < 600) {
      $('.form__description-text').removeClass('form__description-text--active');
    }

    $(window).resize(function() {
      if (screen.width < 600) {
        $('.form__description-text').removeClass('form__description-text--active');
      } else {
        $('.form__description-text').addClass('form__description-text--active');
      }
    });

    $('.img_wr').mouseenter(function() {
      let popup = $('.apartment__popup');
      let top = $(this).offset().top;
      let left = $(this).offset().left + 973;

      if (screen.width < 1300) {
        left = $(this).offset().left + 950;
      }

      $(popup).offset({top:top, left:left});
    });

    // Перечисление квартир и их характеристик, подставляется потом в tooltip
    xAppsArr = [
      {
        apartment: '1',
        status: 'Свободно',
        floor: '1',
        numbersOfRoom: '2',
        area: '44.94',
        kitchenArea: '10.29',
        bathroomArea: '3.24',
        corridorArea: '3.45',
        roomsArea: '28.71',
      },
      {
        apartment: '2',
        status: 'Бронь',
        floor: '1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '3',
        status: 'Свободно',
        floor: '1',
        numbersOfRoom: '1',
        area: '32.94',
        kitchenArea: '12.29',
        bathroomArea: '4.24',
        corridorArea: '4.45',
        roomsArea: '33.71',
      },
      {
        apartment: '4',
        status: 'Продано',
        floor: '1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '5',
        status: 'Бронь',
        floor: '1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '6',
        status: 'Бронь',
        floor: '1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '7',
        status: 'Продано',
        floor: '1',
        numbersOfRoom: '1',
        area: '29.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '8',
        status: 'Свободно',
        floor: '2',
        numbersOfRoom: '2',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '9',
        status: 'Свободно',
        floor: '2',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '10',
        status: 'Бронь',
        floor: '2',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '11',
        status: 'Свободно',
        floor: '2',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '12',
        status: 'Продано',
        floor: '2',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '13',
        status: 'Свободно',
        floor: '2',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '14',
        status: 'Свободно',
        floor: '2',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '15',
        status: 'Свободно',
        floor: '3',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '16',
        status: 'Бронь',
        floor: '3',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '17',
        status: 'Свободно',
        floor: '3',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '18',
        status: 'Продано',
        floor: '3',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '19',
        status: 'Свободно',
        floor: '3',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '20',
        status: 'Свободно',
        floor: '3',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '21',
        status: 'Свободно',
        floor: '3',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '22',
        status: 'Свободно',
        floor: '4',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '23',
        status: 'Продано',
        floor: '4',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '24',
        status: 'Бронь',
        floor: '4',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '25',
        status: 'Свободно',
        floor: '4',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '26',
        status: 'Свободно',
        floor: '4',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '27',
        status: 'Свободно',
        floor: '4',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '28',
        status: 'Продано',
        floor: '4',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '29',
        status: 'Бронь',
        floor: '5',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '30',
        status: 'Свободно',
        floor: '5',
        numbersOfRoom: '2',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '31',
        status: 'Свободно',
        floor: '5',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '32',
        status: 'Свободно',
        floor: '5',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '33',
        status: 'Бронь',
        floor: '5',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '34',
        status: 'Свободно',
        floor: '5',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '35',
        status: 'Продано',
        floor: '5',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '36',
        status: 'Свободно',
        floor: '6',
        numbersOfRoom: '2',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '37',
        status: 'Продано',
        floor: '6',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '38',
        status: 'Свободно',
        floor: '6',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '39',
        status: 'Бронь',
        floor: '6',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '40',
        status: 'Свободно',
        floor: '6',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '41',
        status: 'Бронь',
        floor: '6',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '42',
        status: 'Бронь',
        floor: '6',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '43',
        status: 'Свободно',
        floor: '7',
        numbersOfRoom: '2',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '44',
        status: 'Продано',
        floor: '7',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '45',
        status: 'Бронь',
        floor: '7',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '46',
        status: 'Бронь',
        floor: '7',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '47',
        status: 'Продано',
        floor: '7',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '48',
        status: 'Свободно',
        floor: '7',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '49',
        status: 'Свободно',
        floor: '7',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '50',
        status: 'Бронь',
        floor: '8',
        numbersOfRoom: '2',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '51',
        status: 'Свободно',
        floor: '8',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '52',
        status: 'Свободно',
        floor: '8',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '53',
        status: 'Продано',
        floor: '8',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '54',
        status: 'Бронь',
        floor: '8',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '55',
        status: 'Бронь',
        floor: '8',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '56',
        status: 'Продано',
        floor: '8',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '57',
        status: 'Свободно',
        floor: '9',
        numbersOfRoom: '2',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '58',
        status: 'Продано',
        floor: '9',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '59',
        status: 'Продано',
        floor: '9',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '60',
        status: 'Свободно',
        floor: '9',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '61',
        status: 'Свободно',
        floor: '9',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '62',
        status: 'Бронь',
        floor: '9',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '63',
        status: 'Свободно',
        floor: '9',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '64',
        status: 'Бронь',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '65',
        status: 'Свободно',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '66',
        status: 'Продано',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '67',
        status: 'Свободно',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '68',
        status: 'Свободно',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '69',
        status: 'Свободно',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '70',
        status: 'Свободно',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '71',
        status: 'Свободно',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '72',
        status: 'Бронь',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '73',
        status: 'Продано',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '74',
        status: 'Свободно',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '75',
        status: 'Бронь',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '76',
        status: 'Бронь',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
      {
        apartment: '77',
        status: 'Свободно',
        floor: '-1',
        numbersOfRoom: '1',
        area: '49.94',
        kitchenArea: '13.29',
        bathroomArea: '2.24',
        corridorArea: '4.45',
        roomsArea: '31.71',
      },
    ]

    $( ".floors" ).each(function(xel,xi) {
      let xId = $(this).attr('id');

      let xApartment = {
        status: '',
      };

      xAppsArr.forEach(function(xel,xi) {
        if (('app-' + xel.floor + '-' + xel.apartment) == xId) {
          xApartment = xel;
        }
      });

      $('.status').text(xApartment.status);
    });


    $('.floors').hover(function() {
      let xId = $(this).attr('id');

      let xApartment = {
        status: '',
      };
      xAppsArr.forEach(function(xel,xi) {
        if (('app-' + xel.floor + '-' + xel.apartment) == xId) {
          xApartment = xel;
        }
      });

      $('.status').text(xApartment.status);

      if ($('.status').text() != '') {
        $(this, '.floors').css({'stroke': 'rgba(75, 83, 96, 1)'});
      }

      if ($('.status').text() === 'Бронь') {
        $(this, '.floors').css('fill', 'rgba(255, 255, 0, 0.5)');
      } else if ($('.status').text() === 'Продано') {
        $(this, '.floors').css('fill', 'rgba(255, 0, 0, 0.5)');
      } else if ($('.status').text() === 'Свободно') {
        $(this, '.floors').css('fill', 'rgba(0, 255, 38, 0.5)');
      };
    });

    $('.floors').mouseenter(function() {
      if (!(window.matchMedia('(max-width: 991px)').matches)) {
        let xId = $(this).attr('id');
        let xApartment = {
          apartment: '',
          status: '',
          floor: '',
          numbersOfRoom: '',
          area: '',
          kitchenArea: '',
          bathroomArea: '',
          corridorArea: '',
          roomsArea: '',
        };

        xAppsArr.forEach(function(xel,xi) {
          if (('app-' + xel.floor + '-' + xel.apartment) == xId) {
            xApartment = xel;
          }
        });

        $('.number-apartment').text(xApartment.apartment);
        $('.status').text(xApartment.status);
        $('.floor').text(xApartment.floor);
        $('.numbers-room').text(xApartment.numbersOfRoom);
        $('.area').text(xApartment.area);
        $('.kitchen-area').text(xApartment.kitchenArea);
        $('.bathroom-area').text(xApartment.bathroomArea);
        $('.corridor-area').text(xApartment.corridorArea);
        $('.rooms-area').text(xApartment.roomsArea);
      }
    });

    $('.floors').mouseleave(function() {
      if ($('.status').text() != '') {
        $(this, '.floors').css({'stroke': 'transparent', 'fill': 'transparent'});
      }
    });

  })(jQuery);
